image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: 'Deployment to Production'
        deployment: production
        script:
          - pipe: atlassian/ftp-deploy:0.3.5
            variables:
              USER: oyoautechcomtw
              PASSWORD: lin694s6
              SERVER: www.toyo-autech.com.tw
              REMOTE_PATH: /httpdocs/web
