on:
  push:
    branches:
      - deploy
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: www.toyo-autech.com.tw
        username: oyoautechcomtw
        password: ${{ secrets.toyo_ftp_password }}
        server-dir: httpdocs/web/
